"""User token

Revision ID: c00c29ca9543
Revises: ad2839dd1776
Create Date: 2024-10-11 18:13:24.334153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00c29ca9543'
down_revision: Union[str, None] = 'ad2839dd1776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tokens_id'), 'users_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_users_tokens_token'), 'users_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tokens_token'), table_name='users_tokens')
    op.drop_index(op.f('ix_users_tokens_id'), table_name='users_tokens')
    op.drop_table('users_tokens')
    # ### end Alembic commands ###
